Add StaticBrcode, DynamicBrcode, CreditPreview and BrcodePreview
starkinfra/sdk-ruby pull request #8
Opened 2022-08-24 20:29 UTC by leandro-stark

2022-09-15 17:37 UTC, joaogpw-stark requested changes

2022-09-15 17:37 UTC, joaogpw-stark commented on CHANGELOG.md
> +- tags parameter to PixClaim, PixInfraction, Pix Chargeback, DynamicBrcode and StaticBrcode resources
Mesma coisa do PR de Java. Da pra tirar essa linha porque ta duplicada e a Parte de DynamicBrcode e StaticBrcode não existia, então não faz sentido adicionar parâmetro.

2022-09-15 17:37 UTC, joaogpw-stark commented on CHANGELOG.md
> +- flow parameter to PixClaim resource
Opa, na verdade o flow foi adicionado no Pix Chargeback. No PixClaim ele era agent

2022-09-15 17:37 UTC, joaogpw-stark commented on CHANGELOG.md
> +- agent parameter to query and page methods in PixInfraction and PixChargeback resources
agent foi trocado por flow na verdade. Se não existia agent da pra falar só que o flow foi adicionado.

2022-09-15 17:37 UTC, joaogpw-stark commented on CHANGELOG.md
> +- agent parameter to flow on query and page methods in PixClaim resource
Se o agent foi adicionado não precisa anunciar a mudança para flow

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +notes = StarkInfra::CardMethod.query(
notes -> cards

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +previews = StarkInfra::StaticBrcode.create(
preview - > brcodes

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +previews = StarkInfra::StaticBrcode.create(
Ta quase tudo com previews

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +previews = StarkInfra::DynamicBrcode.create([
Mais previews

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +If the provided digital signature does not check out with the StarkInfra public key, a stark.exception.InvalidSignatureException will be raised.
quebraria essa linha em duas menores

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +    uuid=request.url.get_parameter("uuid"),
`get_uuid(request.url), # you should implement this method to extract the UUID from the request's URL`

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +)
É pra acabar aqui essa parte de verify

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +require('starkinfra')
Isso é a parte de PixRequest parse

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +require('starkinfra')
E esta certo

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +  content: request.url.get_parameter("uuid"),
Mesma coisa aqui. Isso ta errado pq a UUID ve no path e não no body. Na url não tem nada dizendo uuid=wdejhwiuekf.
`get_uuid(request.url), # you should implement this method to extract the UUID from the request's URL`

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +    StarkInfra::DynamicBrcode.response_due(
Aqui a indentação

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +      due: invoices.due,
invoices -> invocie

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +  content: request.url.get_parameter("uuid"),
Mesma coisa aqui

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +      reconciliation_id: invoices.reconciliation_id,
Mesmos erros no instant

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +## Create a BrcodePreview
`Create BrcodePreviews` sendo que isso é um post em batch

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +     StarkInfra::CreditPreview.new(
indentação

2022-09-15 17:37 UTC, joaogpw-stark commented on README.md
> +previews = StarkInfra::CreditPreview.create([
Eu rodaria isso porque é muito grande então muito possivelmente vai ter erro.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/brcodepreview/brcodepreview.rb
> +  # A BrcodePreview is used to get information from a BR Code you received to check the information before paying it.
Colocar isso:

```
  # When you initialize a PixRequest, the entity will not be automatically
  # created in the Stark Infra API. The 'create' function sends the objects
  # to the Stark Infra API and returns the list of created objects.
```

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/brcodepreview/brcodepreview.rb
> +  # - id [string]: BR Code from a Pix payment. This is also de information directly encoded in a QR Code. ex: "00020126580014br.gov.bcb.pix0136a629532e-7693-4846-852d-1bbff817b5a852040000530398654051
Coloca a descrição igual a de python

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/brcodepreview/brcodepreview.rb
> +end
faltou linha vazia no final do arquivo

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/brcodepreview/brcodepreview.rb
> +  # - account_type [string]: Payment receiver account type. ex: "checking"
No ruby todas as strings são definidas com `'` ao invés de `"`

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/cardmethod/cardmethod.rb
> +  # CardMethod's codes are used to define methods filters in IssuingRules.
`method filters`

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/cardmethod/cardmethod.rb
> +    # # Retrieve CardMethod
`CardMethods`

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/cardmethod/cardmethod.rb
> +    # Receive a generator of CardMethods objects available in the Stark Infra API
`CardMethod objects`

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditnote/creditnote.rb
> +  # - expiration [integer]: time interval in seconds between scheduled date and expiration date. ex 123456789
tirou o dois pontos depois do ex

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditnote/creditnote.rb
> +    # - fee [integer]: fee charged by this Invoice. ex: 200 (= R$ 2.00).
Opa pelo o que eu vi em python não tem mais fine e fe no CreditNote

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditnote/creditnote.rb
> +    # - fee [integer]: fee charged by this Invoice. ex: 200 (= R$ 2.00).
Da um check no changelog

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/cardmethod/cardmethod.rb
> +module StarkInfra
Faltaram os imports

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/cardmethod/cardmethod.rb
> +module StarkInfra
Ta assim em outros arquivos tmb

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +class CreditPreview < StarkInfra::Utils::SubResource
Indentação

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +class CreditPreview < StarkInfra::Utils::SubResource
Vai ter que arrumar em baixo tmb

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +  def self.parse_credit(credit, type)
Deixar isso de backlog pra ver se não conseguimos usar o formato o PaymentRequest

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +  # # CreditNotePreview object
Aqui ta errado a indentação mas acredito que quando arrumar ali em cima aqui vai ficar certo.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +  # A CreditNotePreview is used to preview a CCB contract between the borrower and lender with a specific table type.
Acho muito mais organizado deixar objetos diferentes em arquivos diferentes. Isso se aplica pra CreditNote também.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +  # A CreditNotePreview is used to preview a CCB contract between the borrower and lender with a specific table type.
e a invoice do credit note também tem recursos dentro. Da um check na arvore de python.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +  # - invoices [list of Invoice objects]: list of Invoice objects to be created and sent to the credit receiver. ex: invoices=[Invoice(), Invoice()]
[list of CreditNote.Invoice objects]: list of CreditNote.Invoice objects to be created and sent to the credit receiver.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +    def initialize(type:, nominal_amount:, scheduled:, tax_id:, invoices: nil, nominal_interest: nil, initial_due: nil, count: nil, initial_amount: nil, interval: nil, rebate_amount: nil, amount: nil
Quebrar linha

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +    def initialize(type:, nominal_amount:, scheduled:, tax_id:, invoices: nil, nominal_interest: nil, initial_due: nil, count: nil, initial_amount: nil, interval: nil, rebate_amount: nil, amount: nil
a de cima também

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +      return invoices if invoices.nil?
O de invoice tem uma linha vazia aqui depois do returmn

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +    def self.parse_optional_invoice(invoices)
Eu não chamaria de parse_optional_invocies. Da onde isso foi tirado? Têm que arrumar. Se existe a **parseOptionalInvoices** é porque existe a **parseInvoices**. Dai qual seria a diferença entre uma e a outra? A sem optional iria quebrar quando fosse passado um array vazio? Isso não faz sentido porque quem tem que mapear os erros é a API, não o SDK. Principalmente para esse caso que as Invoices são conditionally-required dependendo do tipo do CreditNote

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditsigner/creditsigner.rb
> +    def self.parse_signers(signers)
Tem lugares que a função parse ta dentro da classe indentada e tem lugares que ta fora. Existe uma razão para isso? Se não tiver uma razão é melhor definir um padrão igual para todas as funções de parse.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - created [Date or string]: creation datetime in ISO format of the DynamicBrcode. ex: Date.new(2020, 3, 10)
`Datetime ` e `DateTime.new`

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - created [Date or string]: creation datetime in ISO format of the DynamicBrcode. ex: Date.new(2020, 3, 10)
Mesma coisa para o due

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +      return params.to_json
Isso foi bem testado e comparado com o json de algum outro SDK? Se quiser um json de exemplo tem no getting started

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +      return params.to_json
Tem que confirmar se as datas, discount estão exatamente no formato certo e tal tmb. Se puder coloca ela aqui ou me chama pra dar um check

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - created [Date or string]: creation datetime of the DynamicBrcode. ex: Date.new(2020, 3, 10)
Esse created tmb é DateTime

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - nominal_amount [integer]: positive integer that represents the amount in cents of the resulting Pix transaction. ex: 1234 (= R$ 12.34)
Aqui é amount, não nominal_amount

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    def self.verify(content:, signature:, user: nil)
Aqui é uuid e não content

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    class Discount < StarkInfra::Utils::SubResource
Cadê a Docstrings?

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - expiration [Date or integer, default 86400 (1 day)]: time in seconds counted from the creation datetime until the DynamicBrcode expires. After expiration, the BR code cannot be paid anymore.
Expiration não pode ser um date. Eu troquei isso naquela branch de python que eu falei pra vocês. Falando nisso da um conferida pra ver se todos os pontos que estão no PR estão refletidos aqui: 
https://github.com/starkinfra/sdk-python/tree/fix/disctrings-and-format

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - expiration [Date or integer, default 86400 (1 day)]: time in seconds counted from the creation datetime until the DynamicBrcode expires. After expiration, the BR code cannot be paid anymore.
Isso é o compilado de coisas que fui achando errado no PR de vcs que também estavam errados no python

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - limit [integer, default 100]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
Aqui não é unlimited if nill. Têm que dar um check nos outros arquivos tmb

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - list of PixRequest objects with updated attributes
Ta como PixRequest. Lembra de sempre dar um search no arquivo quando ele for copiado de outro pra conferir. Da um search all pra ver se não tem em outros lugares

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +  # - created [DateTime]: creation datetime for the DynamicBrcode. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
Não pode ser string aqui? Se não puder da um search all em `DateTime or String `. Também confere se  `Date or String ` funciona pros lugares em que data for usada e da um reach all pra arrumar

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +  # - created [DateTime]: creation datetime for the DynamicBrcode. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
Mesma coisa com o updated. E se der pra ser string da um serach em `[Date]` e em `[DateTime]` pra arrumar tmb

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +  # - external_id [string]: string that must be unique among all your DynamicBrcodes. Duplicated external ids will cause failures. ex: "my-internal-id-123456"  # - sender_tax_id [string]: sender tax
Da uma olhada no fim dessa linha tem o sender_tax_id tmb que não deveria estar nessa docstring

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +module StarkInfra
Imports?

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +  # - credit [CreditNotePreview]: Information preview of the informed credit.
[CreditNotePreview object]: CreditNotePreview object containing credit information.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +  # - type [string]: Credit type. ex: "credit-note"
`Credit type, inferred from the payment parameter if it is not a dictionary.`

Esse parâmetro na verdade não é required. Ele só é required se um dicionário for passado no parâmetro credit. Vou arrumar no python e checa aqui também se o create não funciona sem ele.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +  # - type [string]: Credit type. ex: "credit-note"
Se não funcionar têm que arrumar o Credit note tmb porque parece que está igual

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/brcodepreview/brcodepreview.rb
> +  # A BrcodePreview is used to get information from a BR Code you received to check the information before paying it.
Dar um check se não falta em outros

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_issuingproduct.rb
>      bins = nil
bins?

2022-09-15 17:37 UTC, joaogpw-stark commented on CHANGELOG.md
> +- bacen_id parameter from PixChargeback and PixInfraction resources
Faltou falar que tirou o updated do issuing holder. Faz o changelog baseado na planilha de SDKs pra ter ctz que não esqueceu nada.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingcard/issuingcard.rb
> +  # - expiration [DateTime]: [EXPANDABLE] masked card expiration datetime. Expand to unmask the value, ex: DateTime.new(2032, 3, 10, 10, 30, 0, 0)
É pra ser um ponto aqui mesmo

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuinginvoice/issuinginvoice.rb
> +  # - due [datetime.datetime or datetime.date or string]: Invoice due and expiration date in UTC ISO format. ex: "2020-10-28T17:59:26.249976+00:00"
Aqui eu colocaria o exemplo assim: `DateTime.new(2020, 3, 10, 10, 30, 0, 0)`, menos chance de erro. Acho que esse formato ta errado com o T entre a data e a hora. Tem que checar também pra corrigir nos outros lugares

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingpurchase/issuingpurchase.rb
> +  # - issuer_currency_symbol [string]: issuer currency symbol. ex: "$"
Voltar para '

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingpurchase/issuingpurchase.rb
> +                :issuing_transaction_ids, :status, :updated, :created, :is_partial_allowed, :card_tags, :holder_tags
purpose não foi adicionado como parâmetro, só na Docstrings. Tem que prestar bastante atenção nos parâmetros!

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingpurchase/issuingpurchase.rb
> +    def self.parse(content:, signature:, key: nil, user: nil)
key?

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingpurchase/issuingpurchase.rb
> +    def self.parse(content:, signature:, key: nil, user: nil)
Isso é interno da função para fazer o parsing de cada recurso. Olha nos outros sdks.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingpurchase/issuingpurchase.rb
> +    # If the authorization request is not answered within 2 seconds or is not answered with an HTTP status code 200 the IssuingPurchase will go through the pre-configured stand-in validation.
Quebrar essa linha

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingpurchase/issuingpurchase.rb
> +    # def self.response(content:, signature:, key: nil, user: nil)
Wuttt

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingpurchase/issuingpurchase.rb
> +    # # Helps you respond IssuingPurchase requests
Helps you respond to a IssuingPurchase authorization request

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingpurchase/issuingpurchase.rb
> +    # def self.response(content:, signature:, key: nil, user: nil)
A função comentada ta errada tmb e muito provavelmente não tem teste

2022-09-15 17:37 UTC, joaogpw-stark commented on CHANGELOG.md
> +- IssuingInvoice missing parameters
Falei no ultimo PR pra tirar isso e descrever melhor:
```
- IssuingPurchase missing parameters
 - IssuingInvoice missing parameters
```
 Tem que ser específico no changelog.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingrule/issuingrule.rb
> +  # - id [string, default nil]: unique id returned when an IssuingRule is created, used to update a specific IssuingRule. ex: "5656565656565656"
De novo, ruby usa `'` e não `"`. Quando você encontrar muita coisa igual e achar que ta errado, se pergunta se ta errado mesmo antes de mudar.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingrule/issuingrule.rb
> +    end
Os outros parses tão assim, é legal deixar padronizado
Entendo que tem que importar o resource_maker, mas to falando de pular linha ou não
```. 
        def self.parse_discounts(discounts)
          return discounts if discounts.nil?

          parsed_discounts = []
          discounts.each do |discount|
            unless discount.is_a? Discount
              discount = StarkInfra::Utils::API.from_api_json(resource[:resource_maker], discount)
            end
            parsed_discounts << discount
          end
          parsed_discounts
        end
```

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingrule/issuingrule.rb
> +      category_maker = StarkInfra::MerchantCategory.resource[:resource_maker]
chamaria de resource_maker em todos. O escopo das variáveis é dentro da função.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/merchantcountry/merchantcountry.rb
> +    def initialize(code:, short_code:, name:, number:)
e os `:nil`?

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/merchantcategory/merchantcategory.rb
> +    def initialize(code:, type:, name:, number:)
e os `:nil`?

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/pixchargeback/pixchargeback.rb
> +    # Retrieve the PixChargeback object linked to your Workspace in the Stark Infra API using its id.
Retrieve a PixChargeback object linked to your Workspace in the Stark Infra API using its id.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/pixchargeback/pixchargeback.rb
> -    # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
Porque tirou?

2022-09-15 17:37 UTC, joaogpw-stark commented on CHANGELOG.md
> +### Added
Ta faltando coisa da planilha hein. Não mudou o PixDirector pra SubResource.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/pixclaim/pixclaim.rb
> +      type: nil, flow: nil, key_type: nil, key_id: nil, user: nil
Cadê tags aqui?

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/pixclaim/pixclaim.rb
> +      type: nil, flow: nil, key_type: nil, key_id: nil, user: nil
Tags

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/pixdomain/pixdomain.rb
> +  # The PixDomain object displays the domain name and the QR Code domain certificate of Pix participants.
Porque? As métricas do ruby especificam no máximo 80 carácteres por linha. Eu não to comentando isso porque é um trabalho meio que desnecessário mas quando eu quebrei essa linha eu taba pensando nisso hahaha

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/pixinfraction/pixinfraction.rb
>              debited_bank_code: json['debited_bank_code'],
Ta faltando bastante atenção nos parâmetros. **Aqui não tem flow nem tags**. Quando se trata dos parâmetros têm que prestar muita atenção.

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/pixrequest/pixrequest.rb
> +  # - cash_amount [integer, default nil]: Amount to be withdrawal from the cashier in cents. ex: 1000 (= R$ 10.00)
Default aqui é 0

2022-09-15 17:37 UTC, joaogpw-stark commented on CHANGELOG.md
> +- StaticBrcode resource
Faltou falar que tirou o bank_code do PixReversal

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/pixreversal/pixreversal.rb
> +      reversal.external_id != nil  ? reversal.external_id : ""
Python: 
```
    request.fee = request.fee or 0
    request.tags = request.tags or []
    request.external_id = request.external_id or ""
    request.description = request.description or ""
```

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/staticbrcode/staticbrcode.rb
> +  # created in the Stark Infra API. The 'create' function sends the objects
Ta faltando coisa aqui

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/staticbrcode/staticbrcode.rb
> +  # - amount [integer, default 0]: positive integer that represents the amount in cents of the resulting Pix transaction. ex: 1234 (= R$ 12.34)
Eu colocaria aquilo que tem em python.
`positive integer that represents the amount in cents of the resulting Pix transaction. If the amount is zero, the sender can choose any amount in the moment of payment.`

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/staticbrcode/staticbrcode.rb
> +    # - limit [integer, default 100]: maximum number of objects to be retrieved. Unlimited if nil. ex: 35
Não é unlimited if nil

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/staticbrcode/staticbrcode.rb
> +            )
indentação

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/issuingcard/issuingcard.rb
> +  # - product_id [string, default None]: card product ID to which the card is bound. ex: "53810200"
None -> nil

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/utils/parse.rb
> +
tirar essa linha vazia a mais

2022-09-15 17:37 UTC, joaogpw-stark commented on lib/utils/rest.rb
> +        puts payload
Tirar. Da uma revisada no PR inteiro pelo git mesmo sempre antes de mandar pra pegar essas coisinhas e eventualmente mais coisa.

2022-09-15 17:37 UTC, joaogpw-stark commented on test/example_generator.rb
> +      id: '00020126360014br.gov.bcb.pix0114+55119888877775204000053039865802BR5915Jaime Lannister6014Rio de Janeiro62080504123463049402'
Id hardcodada?? Faz uma query, se alguém deletar esse Brcode os testes não funcionam mais.

2022-09-15 17:37 UTC, joaogpw-stark commented on test/example_generator.rb
> +      )
indentação

2022-09-15 17:37 UTC, joaogpw-stark commented on test/example_generator.rb
> +      initial_due: '2022-10-18',
data hardcodada ...

2022-09-15 17:37 UTC, joaogpw-stark commented on test/example_generator.rb
> +      initial_due: '2022-10-18',
Ta assim em todos

2022-09-15 17:37 UTC, joaogpw-stark commented on test/example_generator.rb
> +
Acho mais bonito pular um linha em todos

2022-09-15 17:37 UTC, joaogpw-stark commented on test/example_generator.rb
> +      )
indentação

2022-09-15 17:37 UTC, joaogpw-stark commented on test/example_generator.rb
> +      )
indentação

2022-09-15 17:37 UTC, joaogpw-stark commented on test/example_generator.rb
> +      due: "2022-07-13"
data hardcodada .....

2022-09-15 17:37 UTC, joaogpw-stark commented on test/example_generator.rb
> +      due: "2022-07-01"
data hardcodada .....

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_brcodepreview.rb
> +      [StarkInfra::BrcodePreview.new(id: brcodes[0].id),
ughhhg

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_brcodepreview.rb
> +    static_brcodes = StarkInfra::StaticBrcode.query(limit: 2).to_a
Testaria dynamic tmb que tem parâmetros adicionais

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_cardmethod.rb
> +end
Pular linha no final do arquivo

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_cardmethod.rb
> +    notes.each do |note|
Eu pularia uma linha aqui

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_cardmethod.rb
> +      search: "token",
Aqui não precisa pular uma linha

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_cardmethod.rb
> +      search: "token",
Nem na linha debaixo

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_creditnote.rb
> +    puts credit_note
Não é pra ter puts nos testes

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_creditpreview.rb
> +    credit_note_bullet = ExampleGenerator.creditnote_bullet_example
Lembra de sempre chamar as variáveis pelo último nome. 
1) Quem lê isso acha que é um objeto do tipo CreditNote, e é um CreditNotePreview, eu faria:
`preview_sac = ExampleGenerator.preview_sac_example`

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_creditpreview.rb
> +    credit_note_previewed_types = []
previewed_types -> preview_types
credit_note_previewed_types -> note_types

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_creditpreview.rb
> +    credit_note_preview = [
credit_note_preview -> previews

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_creditpreview.rb
> +    credit_note_preview = [
Lembra que nosso padrão é fazer assim depois:
`previews = StarkInfra::CreditPreview.create(previews)`

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_creditpreview.rb
> +    expect(previewed_types).must_equal(expected_types)
Coloca um deles primeiro dos dois. Ou o expected primeiro ou o normal primeiro

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_creditpreview.rb
> +    expected_types = %w[credit-note credit-note credit-note credit-note]
expected_preview_types

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_creditpreview.rb
> +    expect(previewed_types).must_equal(expected_types)
```
    expect(preview_types).must_equal(expected_preview_types)
    expect(note_types).must_equal(expected_note_types)
```

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_dynamicbrcode.rb
> +    puts due
Têm como fazer a verificação dos paramentos usando os checks da api

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_merchantcategory.rb
> +      puts category
Eu tiraria o puts e faria um check pra ver se esses objetos não estão vazios. Checando algum dos parâmetros deles

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_merchantcountry.rb
> +      puts country
Mesma coisa aqui

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_pixclaim.rb
> +      type: 'ownership',
Eu testaria os parâmetros novos pra ver se ta tudo em ordem. isso para todos os recursos em que os parâmetros foram adicionados (parâmetros: tags e flow) (recursos: PixClaim, Infraction, Chargeback, DynamicBrcode e StaticBrcode). Isso é bom porque também testa  API pra previnir Huston quando nossos clientes usarem a API.

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_pixinfraction.rb
> +    infraction = StarkInfra::PixInfraction.get(get_infraction('fraud'))
Aqui tem que fazer o filtro pro flow e por status. Você só pode cancelar infractions que têm status de delivered e flow out. Type não tem nd a ver.

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_pixinfraction.rb
> +    infraction = StarkInfra::PixInfraction.get(get_infraction('fraud'))
Aqui tem que fazer o filtro pro flow e por status. Você só pode fazer o update (responder) infractions que têm status de delivered e flow in. Type não tem nd a ver.

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_pixinfraction.rb
> +    infraction = StarkInfra::PixInfraction.get(get_infraction('fraud'))
Mesma coisa para Pix Chargeback

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_pixinfraction.rb
> +    infraction = StarkInfra::PixInfraction.get(get_infraction('fraud'))
mesma coisa para PixChargeback

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_pixrequest.rb
> +    puts response
Eu utilizaria um check aqui para confirmar se os parâmetros tão vindo com o formato certo

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_pixreversal.rb
> +    puts StarkInfra::EndToEndIdTest.get_to_reverse
Sem puts

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_staticbrcode.rb
> +      ).to_a
Indentação também aqui, eu colocaria tudo inline aqui

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_staticbrcode.rb
> +      puts brcode
sem putssss

2022-09-15 17:37 UTC, joaogpw-stark commented on test/starkinfra/test_staticbrcode.rb
> +      puts brcode
Tem que fazer testes que se testam sozinhos!x

2022-09-19 18:09 UTC, leandro-stark commented on lib/creditnote/creditnote.rb
> +    # - fee [integer]: fee charged by this Invoice. ex: 200 (= R$ 2.00).
Esse fee não é do CreditNote e sim da Transfer.

2022-09-20 19:57 UTC, leandro-stark commented on README.md
> +previews = StarkInfra::CreditPreview.create([
Foi rodado o que coloquei no README

2022-09-20 20:22 UTC, leandro-stark commented on lib/creditpreview/creditpreview.rb
> +    def self.parse_optional_invoice(invoices)
Não achei essa função nos arquivos. Vou ver contigo depois.

2022-09-20 20:32 UTC, leandro-stark commented on lib/creditsigner/creditsigner.rb
> +    def self.parse_signers(signers)
A única função de Parse que está indentada é a do parse_discounts do objeto Discount do DynamicBrcode, vou ver contigo porque não tem mt sentido colocar a função parse_discounts no DynamicBrcode sem ser dentro do Discount.

2022-09-20 20:46 UTC, leandro-stark commented on lib/issuinginvoice/issuinginvoice.rb
> +  # - due [datetime.datetime or datetime.date or string]: Invoice due and expiration date in UTC ISO format. ex: "2020-10-28T17:59:26.249976+00:00"
Tinha alguns lugares nesse formato msm, pois copiei de Python, mas ja ajeitei.

2022-09-20 21:10 UTC, leandro-stark commented on lib/issuingrule/issuingrule.rb
> +    end
Os parses padrões agora estão todos padronizados, com exceção do parse_signer e o parse_payment que são distintos dos demais.

2022-09-20 21:13 UTC, leandro-stark commented on lib/issuingrule/issuingrule.rb
> +      category_maker = StarkInfra::MerchantCategory.resource[:resource_maker]
Muito mais clean

2022-09-20 21:15 UTC, leandro-stark commented on lib/pixchargeback/pixchargeback.rb
> -    # - user [Organization/Project object, default nil]: Organization or Project object. Not necessary if StarkInfra.user was set before function call
Tirei porque não tinha em Python e fui no automático, mas ja ajeitei. Vou dar um SearchAll depois.

2022-09-20 21:20 UTC, leandro-stark commented on lib/pixreversal/pixreversal.rb
> +      reversal.external_id != nil  ? reversal.external_id : ""
É o equivalente em Ruby

2022-09-20 21:22 UTC, leandro-stark commented on lib/staticbrcode/staticbrcode.rb
> +  # created in the Stark Infra API. The 'create' function sends the objects
O que está faltando? Conferi em Python na mesma branch das fixes e está igual.

2022-09-21 17:54 UTC, leandro-stark commented on CHANGELOG.md
> +- agent parameter to flow on query and page methods in PixClaim resource
O agent foi adicionado para query and page do PixInfraction and PixChargeback, no PixClaim o agent foi alterado para flow no query and page. São coisas diferentes, não?

2022-09-21 17:57 UTC, leandro-stark commented on lib/creditpreview/creditpreview.rb
> +  def self.parse_credit(credit, type)
Não tem como. Passei 1 dia inteiro tentando deixar igual o PaymentRequest, o Dotts que me ajudou a identificar o que estava faltando.

2022-09-21 18:25 UTC, leandro-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +      return params.to_json
Dei um check, mas se quiser podemos rodar de novo.

2022-09-21 18:40 UTC, leandro-stark commented on lib/pixdomain/pixdomain.rb
> +  # The PixDomain object displays the domain name and the QR Code domain certificate of Pix participants.
Não lembro o motivo específico de ter deixado tudo na mesma linha, mas ja ajustei.

2022-09-21 18:46 UTC, leandro-stark commented on test/starkinfra/test_brcodepreview.rb
> +    static_brcodes = StarkInfra::StaticBrcode.query(limit: 2).to_a
Era pra adicionar uma query também para DynamicBrcode? Não entendi mt bem.

2022-09-21 18:47 UTC, leandro-stark commented on test/starkinfra/test_creditnote.rb
> +    puts credit_note
Tava testando só pra ver printando e acabei esquecendo de tirar.

2022-09-22 19:33 UTC, leandro-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +      return params.to_json
Due: {"version":1,"created":"2020-03-10T10:30:00.000000+00:00","due":"2020-03-10T10:30:00.000000+00:00","keyId":"+5511989898989","status":"paid","reconciliationId":"cd65c78aeb6543eaaa0170f68bd741ee","nominalAmount":100,"senderName":"Jamie Lannister","receiverName":"Anthony Edward Stark","receiverStreetLine":"Av. Paulista, 200","receiverCity":"Sao Paulo","receiverStateCode":"SP","receiverZipCode":"01234-567","expiration":"82000","senderTaxId":"20.018.183/0001-8","receiverTaxId":"012.345.678-90","fine":2,"interest":1,"discounts":[{"percentage":3,"due":"2022-09-25"},{"percentage":5,"due":"2022-09-25"}],"description":"Java test"}

Instant: {"version":1,"created":"2020-03-10T10:30:00.000000+00:00","keyId":"+5511989898989","status":"paid","reconciliationId":"cd65c78aeb6543eaaa0170f68bd741ee","amount":1000,"cashierType":"merchant","cashierBankCode":"20018183","cashAmount":1000,"expiration":"82000","senderName":"Anthony Edward Stark","senderTaxId":"20.018.183/0001-8","amountType":"fixed","description":"Java test"}

2022-09-22 20:07 UTC, leandro-stark commented on lib/issuingpurchase/issuingpurchase.rb
> +                :issuing_transaction_ids, :status, :updated, :created, :is_partial_allowed, :card_tags, :holder_tags
Revisei todos os parâmetros e docstrings. Tudo correto

2022-09-22 20:26 UTC, leandro-stark commented on CHANGELOG.md
> +- bacen_id parameter from PixChargeback and PixInfraction resources
Dei um check geral

2022-09-22 21:17 UTC, leandro-stark commented on CHANGELOG.md
> +- agent parameter to flow on query and page methods in PixClaim resource
Ok
by: eu

2022-09-22 21:24 UTC, leandro-stark commented on lib/creditpreview/creditpreview.rb
> +  def self.parse_credit(credit, type)
vc que sabe

2022-09-23 20:17 UTC, leandro-stark commented on lib/creditpreview/creditpreview.rb
> +  # - type [string]: Credit type. ex: "credit-note"
Tudo funcionando

2022-09-26 21:33 UTC, joaogpw-stark requested changes

2022-09-26 21:33 UTC, joaogpw-stark commented on CHANGELOG.md
> +- flow parameter to query and page methods in PixClaim resource
flow não foi adicionado no PixClaim. Agent trocou para flow

2022-09-26 21:33 UTC, joaogpw-stark commented on CHANGELOG.md
> +- expand parameter to IssuingHolder
Especifica em qual método o expand foi adicionado. Do jeito que ta parece que foi no objeto msm

2022-09-26 21:33 UTC, joaogpw-stark commented on CHANGELOG.md
> +- tax_amount attribute in CreditNote resource
added to não in

2022-09-26 21:33 UTC, joaogpw-stark commented on CHANGELOG.md
> +- nominal_interest attribute to CreditNote resource
Da pra juntar isso com o tax_amount pra usar uma linha só

2022-09-26 21:33 UTC, joaogpw-stark commented on CHANGELOG.md
> +- due, link and brcode attributes missing in IssuingInvoice resource
Essas últimas 3 linhas dizem a mesma coisa. Usa a primeira

2022-09-26 21:33 UTC, joaogpw-stark commented on CHANGELOG.md
> +- nominal_interest attribute to CreditNote resource
Falaria que é um atributo return-only

2022-09-26 21:33 UTC, joaogpw-stark commented on CHANGELOG.md
> +- flow attribute in PixChargeback resource
Não falo que tirou o update IssuingHolder

2022-09-26 21:33 UTC, joaogpw-stark commented on README.md
> +cards = StarkInfra::CardMethod.query(
**Mals eu que falei pra botar cards mas me confundi. Aqui seria methods**

2022-09-26 21:33 UTC, joaogpw-stark commented on README.md
> +  id: '5155165527080960',
No ruby a gente não passa a key "id", acho que não funciona

2022-09-26 21:33 UTC, joaogpw-stark commented on README.md
> +previews = StarkInfra::DynamicBrcode.create([
Marcou como resolvido? Aqui é um DynamicBrcode não um BrcodePreview. 
Previews -> brcodes

2022-09-26 21:33 UTC, joaogpw-stark commented on README.md
> +previews = StarkInfra::DynamicBrcode.query(
Aqui também

2022-09-26 21:33 UTC, joaogpw-stark commented on README.md
> +    uuid=request.url.get_uuid(request.url), # you should implement this method to extract the UUID from the request's URL
request.url.get_uuid(request.url) -> get_uuid(request.url)

2022-09-26 21:33 UTC, joaogpw-stark commented on README.md
> +  content: request.url.get_uuid(request.url), # you should implement this method to extract the UUID from the request's URL
Mesma coisa aqui

2022-09-26 21:33 UTC, joaogpw-stark commented on README.md
> +  content: request.url.get_uuid(request.url), # you should implement this method to extract the UUID from the request's URL
Aqui tmb

2022-09-26 21:33 UTC, joaogpw-stark commented on README.md
> +
Não precisa pular essa linha

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditnote/invoice/discount.rb
> +  # - due [DateTime, Date.new or string]: due datetime for the discount
a tipagem aqui ta errada tmb

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditnote/invoice/discount.rb
> +  # - due [DateTime, Date.new or string]: due datetime for the discount
[DateTime or string]

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditnote/invoice/invoice.rb
> +  # - due [DateTime, Date.new or string, default now + 2 days]: Invoice due date in UTC ISO format. DateTime.new(2020, 3, 10, 10, 30, 0, 0) for immediate invoices and '2020-10-28' for scheduled invoi
Segunda vez que vejo esse erro: 
DateTime, Date.new or string - > DateTime or string

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditnote/invoice/invoice.rb
> +  # - due [DateTime, Date.new or string, default now + 2 days]: Invoice due date in UTC ISO format. DateTime.new(2020, 3, 10, 10, 30, 0, 0) for immediate invoices and '2020-10-28' for scheduled invoi
Da um search all

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditnote/invoice/invoice.rb
> +  # - discounts [list of Discount objects]: list of Discount objects. ex: [Discount.new()]
Eu especificaria que isso é um CrditNote::Invoice, mesma coisa para os outros objetos que fazem parte dos outros

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditnote/log.rb
> +    # - created [DateTime or DateTime.new]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
Porque isso? 
DateTime.new não é uma classe e sim uma inicialização do objeto da classe DateTime

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditnote/log.rb
> +      # - after [Date, Date.new or string, default nil]: date filter for objects created only after specified date. ex: Date.new(2020, 3, 10)
Mesma coisa aqui tem que arrumar em todos os lugares

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditpreview/creditnotepreview.rb
> +
Não precisa pular essa linha

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditpreview/creditnotepreview.rb
> +  # - invoices [list of CreditNote.Invoice objects]: list of CreditNote.Invoice objects to be created and sent to the credit receiver.
`CreditNote.Invoice -> CreditNote::Invoice`
Search all

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +  # - credit [CreditNotePreview or hash]: Information preview of the informed credit.
Todos os parâmetros de um objeto são um outro objeto, tipo a invoice do CreditNote tem que tambem podem ser um hash. Dai tem que arrumar as docstrings só

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/creditpreview/creditpreview.rb
> +  # - credit [CreditNotePreview or hash]: Information preview of the informed credit.
Dai na parte do create não precisa definir isso na doscring, que nem você fez no webhook. Não me pergunte o porque mas não precisa hahaha, acho que nosso padrão é falar que pode só no readme mesmo

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - created [Date or string]: creation datetime in ISO format of the DynamicBrcode. ex: Date.new(2020, 3, 10)
o .new era para o exemplo

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +  # - created [DateTime or string]: creation datetime for the DynamicBrcode. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
Esse na verdade nunca vai ser string porque é um atributo return-only, que o nosso SDK sempre converte no objetp DateTime. Arruma nos outros também?

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - created [Date or string]: creation datetime in ISO format of the DynamicBrcode. ex: "2020-03-10T10:30:00.000000+00:00"
aqui é datetime

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - due [Date.new or string]: requested payment due datetime in ISO format. ex: "2020-03-10T10:30:00.000000+00:00"
Aqui tmb, eu já tinha comentado isso hein

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - expiration [integer]: time in seconds counted from the creation datetime until the DynamicBrcode expires. After expiration, the BR Code cannot be paid anymore.
Opa, aproveita e já da um check pra ver se as docstrings dos outros expirations estão certas. lembra que é semore inteiro

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - expiration [integer]: time in seconds counted from the creation datetime until the DynamicBrcode expires. After expiration, the BR Code cannot be paid anymore.
A não ser no IssuingCard

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/issuingbalance/issuingbalance.rb
> +  # - updated [DateTime or string]: latest update datetime for the IssuingBalance. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
Aqui não pode ser string, é return-only e o SDK sempre converte em DateTime

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/issuingcard/log.rb
> +    # - created [DateTime or string]: creation datetime for the log. ex: DateTime.new(2020, 3, 10, 10, 30, 0, 0)
Mesma coisa aqui

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/issuingpurchase/issuingpurchase.rb
> +  ## Attributes (return-only):
Aqui o padrão é assim: 
`# ## `

2022-09-26 21:33 UTC, joaogpw-stark commented on README.md
> +  search: "brazil"
`"` -> `'`
Da um search all por favor

2022-09-26 21:33 UTC, joaogpw-stark commented on README.md
> +  search: "brazil"
Tem mais lugares errados

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/merchantcategory/merchantcategory.rb
> +    def initialize(code: nil, type: nil, name: nil, number: nil)
Os parâmetros required não precisam de : nill

2022-09-26 21:33 UTC, joaogpw-stark commented on lib/utils/parse.rb
> +
Não tirou

2022-09-27 14:43 UTC, leandro-stark commented on CHANGELOG.md
> +- flow attribute in PixChargeback resource
Não tirei o updated do IssuingHolder, não entendi.

2022-09-27 14:45 UTC, leandro-stark commented on README.md
> +  id: '5155165527080960',
Funciona.

2022-09-27 20:37 UTC, leandro-stark commented on lib/creditpreview/creditpreview.rb
> +  # - credit [CreditNotePreview or hash]: Information preview of the informed credit.
Copiei dos mesmo lugares que tem no Python na docstring que aceitam hash (ou dicionário em Python)

2022-09-30 20:28 UTC, joaogpw-stark requested changes

2022-09-30 20:28 UTC, joaogpw-stark commented on lib/dynamicbrcode/dynamicbrcode.rb
> +    # - created [DateTime or string]: creation datetime of the DynamicBrcode. ex: "2020-03-10T10:30:00.000000+00:00" or DateTime.new(2020, 3, 10, 10, 30, 0, 0).
Nesse arquivo ainda tem um Date.new(), da um search all em `.new()` por favor

2022-09-30 20:28 UTC, joaogpw-stark commented on lib/creditpreview/creditnotepreview.rb
> +  # - nominal_amount [integer]: amount in cents transferred to the credit receiver, before deductions. ex: 11234 (= R$ 112.34)
Comentei aqui porque não tem outro lugar, e do webhook me chama que eu te explico dai

2022-09-30 20:28 UTC, joaogpw-stark commented on lib/creditpreview/creditnotepreview.rb
> +  # - nominal_amount [integer]: amount in cents transferred to the credit receiver, before deductions. ex: 11234 (= R$ 112.34)
E voce testou se o response aceita datetime? 
Quero ver o output

2022-09-30 21:15 UTC, leandro-stark commented on lib/creditpreview/creditnotepreview.rb
> +  # - nominal_amount [integer]: amount in cents transferred to the credit receiver, before deductions. ex: 11234 (= R$ 112.34)
Passando o DateTime, esse é o output:

{"version":1,"created":"2020-03-10T10:30:00+00:00","due":"2020-03-10T10:30:00+00:00","keyId":"+5511989898989","status":"paid","reconciliationId":"cd65c78aeb6543eaaa0170f68bd741ee","nominalAmount":100,"senderName":"Jamie Lannister","receiverName":"Anthony Edward Stark","receiverStreetLine":"Av. Paulista, 200","receiverCity":"Sao Paulo","receiverStateCode":"SP","receiverZipCode":"01234-567","expiration":"82000","senderTaxId":"20.018.183/0001-8","receiverTaxId":"012.345.678-90","fine":2,"interest":1,"discounts":[{"percentage":3,"due":"2022-10-03"},{"percentage":5,"due":"2022-10-03"}],"description":"Java test"}

2022-09-30 21:16 UTC, leandro-stark commented on lib/creditpreview/creditnotepreview.rb
> +  # - nominal_amount [integer]: amount in cents transferred to the credit receiver, before deductions. ex: 11234 (= R$ 112.34)
Isso foi o que eu enviei:

due = StarkInfra::DynamicBrcode.response_due(
      version: 1,
      created: DateTime.new(2020, 3, 10, 10, 30, 0, 0),
      due: DateTime.new(2020, 3, 10, 10, 30, 0, 0),
      key_id: '+5511989898989',
      status: 'paid',
      reconciliation_id: 'cd65c78aeb6543eaaa0170f68bd741ee',
      nominal_amount: 100,
      sender_name: 'Jamie Lannister',
      receiver_name: 'Anthony Edward Stark',
      receiver_street_line: 'Av. Paulista, 200',
      receiver_city: 'Sao Paulo',
      receiver_state_code: 'SP',
      receiver_zip_code: '01234-567',
      expiration: '82000',
      sender_tax_id: '20.018.183/0001-8',
      receiver_tax_id: '012.345.678-90',
      fine: 2,
      interest: 1,
      discounts: discount,
      description: 'Java test'
    )

2022-09-30 21:44 UTC, merged